[test111]
color = "c2e0c6"
name = "test111"
description = ""

["不具合"]
color = "ee0701"
name = "不具合"
description = "bug"

["保留"]
color = "ffffff"
name = "保留"
description = "wontfix"

["提案"]
color = "fbca04"
name = "提案"
description = "enhancement"

["無効"]
color = "e6e6e6"
name = "無効"
description = "invalid"

["相談"]
color = "33aa3f"
name = "相談"
description = "help wanted"

["質問"]
color = "cc317c"
name = "質問"
description = "question"

["重複"]
color = "cccccc"
name = "重複"
description = "duplicate"
