[bug]
color = "ee0701"
name = "bug"
description = "bug"

["modify by github"]
color = "c2e0c6"
name = "modify by github"
description = ""

[test111]
color = "e99695"
name = "test111"
description = ""

[test222]
color = "fcae64"
name = "test222"
description = ""

[wontfix]
color = "ffffff"
name = "wontfix"
description = "wontfix"

["緊急度：高"]
color = "b60205"
name = "緊急度：高"
description = "カスタム"

["質問"]
color = "cc317c"
name = "質問"
description = "question"

["重複"]
color = "cccccc"
name = "重複"
description = "duplicate"
