[bug]
color = "ee0701"
name = "bug"
description = "bug"

[enhancement]
color = "fbca04"
name = "enhancement"
description = "enhancement"

[invalid]
color = "e6e6e6"
name = "invalid"
description = "invalid"

[test1]
color = "d4c5f9"
name = "test1"
description = ""

[test2]
color = "4937b2"
name = "test2"
description = ""

[wontfix]
color = "ffffff"
name = "wontfix"
description = "wontfix"

["相談"]
color = "33aa3f"
name = "相談"
description = "help wanted"

["緊急度：中"]
color = "ffff00"
name = "緊急度：中"
description = "カスタム"

["緊急度：低"]
color = "0e8a16"
name = "緊急度：低"
description = "カスタム"

["緊急度：高"]
color = "b60205"
name = "緊急度：高"
description = "カスタム"

["質問"]
color = "cc317c"
name = "質問"
description = "question"

["重複"]
color = "cccccc"
name = "重複"
description = "duplicate"
