["不具合"]
color = "ee0701"
name = "不具合"
description = "bug"

["保留"]
color = "ffffff"
name = "保留"
description = "wontfix"

["提案"]
color = "fbca04"
name = "提案"
description = "enhancement"

["無効"]
color = "e6e6e6"
name = "無効"
description = "invalid"

["相談"]
color = "33aa3f"
name = "相談"
description = "help wanted"

["緊急度：中"]
color = "ffff00"
name = "緊急度：中"
description = "カスタム"

["緊急度：低"]
color = "0e8a16"
name = "緊急度：低"
description = "カスタム"

["緊急度：高"]
color = "b60205"
name = "緊急度：高"
description = "カスタム"

["質問"]
color = "cc317c"
name = "質問"
description = "question"

["重複"]
color = "cccccc"
name = "重複"
description = "duplicate"

["test"]
color = "cccccc"
name = "重複"
description = "duplicate"